name = "netlens"
main = "src/index.ts"
compatibility_date = "2026-05-20"

[[rules]]
type = "Text"
globs = ["**/*.html?raw", "**/*.css?raw", "**/*.js?raw"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "netlens-geoip"
database_id = "3e4da3f5-a559-4475-b742-f12f57fa04a6"
